// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_0S9AtvkK6_cztqjBpElrllMK_smWjQ',
    appId: '1:501040938403:web:191893236f7fdef5966e16',
    messagingSenderId: '501040938403',
    projectId: 'rendezvous-99d50',
    authDomain: 'rendezvous-99d50.firebaseapp.com',
    storageBucket: 'rendezvous-99d50.appspot.com',
    measurementId: 'G-0RMG2MSWR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqYhf4II8j0FfdLhGi2TafIaMNwtlKunA',
    appId: '1:501040938403:android:c6348bc0116641d4966e16',
    messagingSenderId: '501040938403',
    projectId: 'rendezvous-99d50',
    storageBucket: 'rendezvous-99d50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgCUBpEOi1lUXAbTQ82AS9Gc_fTUR7yrU',
    appId: '1:501040938403:ios:fc56c7df23f1cf84966e16',
    messagingSenderId: '501040938403',
    projectId: 'rendezvous-99d50',
    storageBucket: 'rendezvous-99d50.appspot.com',
    iosBundleId: 'com.bebop.rendezvous',
  );
}
